language: python
python:
  - "2.7"
  - "3.6"
  - "nightly"
  - "pypy3"
install:
  - pip install --upgrade pip
  - pip install numpy
  - pip install tensorflow
  - pip install keras
  - pip install pycodestyle
  - pip install coverage
  - pip install coveralls
before_script:
  - bash lint.sh
script:
  - bash test.sh
after_success:
  coveralls
